---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Generate Nginx configuration from template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart Nginx

- name: Ensure Nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes
- name: Restart Nginx
  service:
    name: nginx
    state: restarted
